---
AWSTemplateFormatVersion: "2010-09-09"

Description: IAM Roles and Policies

Resources:

  RoleAdministrator:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::676197543816:root
            Action: sts:AssumeRole
            # Condition:
            #  Bool:
            #    "aws:MultiFactorAuthPresent": true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: Administrator

  RoleViewOnly:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::676197543816:root
            Action: sts:AssumeRole
            # Condition:
            #   Bool:
            #     "aws:MultiFactorAuthPresent": true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      RoleName: ViewOnly
